#!/bin/bash

#arm-none-eabi-gdb -iex "set auto-load safe-path /" build-metro_m0_express/firmware.elf
GDB_BIN="arm-none-eabi-gdb"

$GDB_BIN -ex "target extended-remote 127.0.0.1:2331" build-metro_m0_express/firmware.elf


